### ISSUE TITLE
System get sleep when playing video

### ISSUE THREAD

**Issue by LIznzn** [lhc70000/iina#399] opened 2017-02-16 11:32 UTC
**System and IINA version:**

- macOS 10.12.2
- IINA 0.0.5

**Expected hehavior:**

Prevent my Mac from sleeping when I playing video.

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**Comment by lhc70000** [comment] 2017-02-16 12:06
Cannot reproduce.

The related code didn't change at all in previous few versions, and it should show an alert "Cannot prevent display sleep" if it failed preventing sleep.

Please state how often this happens in issue template.

**Comment by Tomn94** [comment] 2017-02-18 12:45
Happened to me too while I was not plugged in.

I cannot state whether it comes from this version or not, if it was because I was not plugged in or not (I rarely use my MacBook battery). My MacBook Pro restarted and I can't reproduce the issue at the moment.

**Comment by alejx** [comment] 2017-02-20 22:23
Cannot reproduce either. I'm using the latest macOS version. I noticed that @LIznzn is using macOS 10.12.2. Just a guess, @Tomn94 , does that bug only happened on 10.12.2, but cannot reproduce after upgrading the system? If that is true, then this bug should be a macOS 10.12.2 bug.

**Comment by Tomn94** [comment] 2017-02-21 05:04
Oh I didn't mention I was on macOS 10.2.3 because I thought 10.2.2 was the last version. I'm using IINA 0.0.5, but I still can't reproduce this.

**Comment by binux** [comment] 2017-03-03 22:57
macOS 10.12.3
IINA 0.0.6 build 14

same issue here

**Comment by Tomn94** [comment] 2017-03-04 17:31
Happening right now again on IINA 0.0.6/macOS 10.12.3.
I restarted my Mac, launched IINA (no problem occurring), quit IINA then reopened it and it's now occurring.
Can I help & provide something?

**Comment by lhc70000** [comment] 2017-03-09 14:49
Found the bug: sleep prevent/allow function is not triggered when pause/resume by right click.

Will fix soon.

**Comment by lhc70000** [comment] 2017-03-28 12:17
Fixed in 0.0.7.

**Closed by lhc70000** 2017-03-28 12:17 UTC
Labels: bug
