### ISSUE TITLE
0.0.13 crashes on launch - High Sierra

### ISSUE THREAD

**Issue by shila77** [lhc70000/iina#1117] opened 2017-10-16 22:18 UTC
See attached log...

[iina 0..013 crash.pdf](https://github.com/lhc70000/iina/files/1389206/iina.0.013.crash.pdf)

**System and IINA version:**

- macOS 10.13
- IINA 0.0.12

**Comment by saagarjha** [comment] 2017-10-16 22:39
Duplicate of #1099.

**Closed by saagarjha** 2017-10-16 22:39 UTC
