### ISSUE TITLE
Force touch fast backward function does not work properly

### ISSUE THREAD

**Issue by Mayrixon** [lhc70000/iina#930] opened 2017-07-30 16:28 UTC
**System and IINA version:**

- macOS 10.12.6
- IINA 0.0.12 Build 37

**Expected behavior:**

Fast backward speed should be 2x at beginning, and becomes 4x, 8x, and so on, as behavor of fast forward speed.

**Actual behavior:**
Fast backward speed would be 0.5x at beginning, and then 0.25x, 0.12x, and so on.

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**
Every time.

**Comment by saagarjha** [comment] 2017-07-30 18:04
Duplicate of #470.

**Closed** 2017-08-07 10:59 UTC
Labels: other: duplicate
