### ISSUE TITLE
Shuffle as option

### ISSUE THREAD

**Issue by ycuk** [lhc70000/iina#1774] opened 2018-06-08 04:38 UTC
Please do not shuffle playlist rows. I think it should be option that will the random jumping on rows. So the "Next" action should play random row rather than the next row.

Thanks for the free cool player.

1.0.0-beta2 build 80

**Comment by danleyzberg** [comment] 2018-06-23 18:01
I'd like this too!

Thanks!

**Comment by alejx** [comment] 2018-07-04 10:08
Duplicate of #718.

**Closed by alejx** 2018-07-04 10:08 UTC
Labels: type: feature request
