### ISSUE TITLE
Force touch to control speed does not work

### ISSUE THREAD

**Issue by LeoNatan** [lhc70000/iina#240] opened 2017-01-23 08:54 UTC
Has this intentionally been disabled?
Since 0.0.3, I cannot use force touch to control the fast forward speed.

**Comment by saagarjha** [comment] 2017-01-23 08:56
I can tell seem to reproduce this; I'm on 0.3 as well. Have you tried restarting IINA?

**Comment by LeoNatan** [comment] 2017-01-23 08:57
Restarting is an indication of a bug.
But I have, yes.

Let me know what you need to debug. I won't have time to drill in the code too much, unfortunately.

**Comment by saagarjha** [comment] 2017-01-23 09:09
If you can get a reproducible test case, that would be great. I've come to believe that this is a Cocoa bug, since I've been having this intermittently and have been able to resolve it by restarting the app or by flipping the Force Touch switch in the Trackpad pane of System Preferences. If you can figure out what's causing it, I'll look into it and if necessary file a Radar.

**Comment by LeoNatan** [comment] 2017-04-08 22:59
@alejx @saagarjha Still reproduces on the latest release. Disabling force touch does not help. I do not believe this is a Cocoa issue, but indeed an iina issue. When force pressing on the << and >> buttons, I feel a strange rumble, but the speed does not change.

**Comment by LeoNatan** [comment] 2017-05-17 06:59
@alejx @saargarjha Any news? This is no longer "pending confirmation".

**Comment by LeoNatan** [comment] 2017-05-17 07:01
CC @lhc70000

**Comment by alejx** [comment] 2017-07-01 14:54
@LeoNatan I still cannot reproduce it. Can you try it now?

**Comment by saagarjha** [comment] 2017-07-05 03:03
@alejx I can reproduce it, but not reliably (it's very intermittent). I'm not sure what the underlying issue is, though.

**Comment by LeoNatan** [comment] 2017-07-05 05:28
Reliable for me. Just doesn’t work.

**Comment by saagarjha** [comment] 2017-07-05 05:33
So just to confirm:

1. This reproduces on the latest build (compiled or from source).
2. This applies only to IINA, and not to other apps such as QuickTime.
3. The issue is not resolved by:
* Restarting IINA.
* Flipping the switch in System Preferences to enable Force Touch.
* Restarting the computer.

If the above are true, would you be willing to adding breakpoints to the code to help me debug the issue? I'll let you know where to put them and what conditions to add.

**Comment by LeoNatan** [comment] 2017-07-09 09:06
@saagarjha Yes, willing to help debug this. I will be free this weekend.

**Comment by NathanJang** [comment] 2017-07-11 16:59
I just installed the latest version of IINA (0.0.11 build 29). Force-touching the arrows changes the playback speed most of the time, but sometimes pressing harder or releasing it gives unexpected playback speeds; for instance, force-touching to 32x speed and then releasing means the video continues to play at 32x for a few seconds, and only then continues playback at 1x.

**Comment by lhc70000** [comment] 2018-04-04 06:15
@NathanJang It should be a constraint of mpv.

@LeoNatan Closing this issue. Please reopen if the problem persists.

**Closed by lhc70000** 2018-04-04 06:15 UTC
Labels: bug: general
