### ISSUE TITLE
Unable to activate "full screen" mode

### ISSUE THREAD

**Issue by charlesli2000** [lhc70000/iina#1637] opened 2018-04-20 00:51 UTC
**System and IINA version:**

- macOS 10.13.4
- IINA 1.0.0 beta1 Build 71 mpv 0.27.0

**Expected behavior:**

Double click Mouse to activate full screen mode

I have beeen following the setup menu to turn  "Double click mouse"  onto "Enter full screen mode".

Whenever I am watching the movie, and trying to double click the mouse, it never enters into the full screen mode. 

I can enter into the full screen mode only when I  press "F" or press the pre-assigned "full screen" icon at the lower right corner.

When the movie is in full screen mode,  I double click the mouse, it can turn off the full screen mode successfully. However, when I try to double click again. It never turns to full mode.

**Actual behavior:**

Turn to on and off Full Screen mode whenever I double click the mouse.

**Comment by alejx** [comment] 2018-07-05 08:37
Are you using a track pad or a mouse?

**Comment by shrx** [comment] 2018-07-05 17:33
A Logitech USB mouse.

**Comment by lhc70000** [comment] 2018-09-22 17:12
I think it's a duplicate of #39.

**Closed by lhc70000** 2018-09-22 17:12 UTC
Labels: other: duplicate
