### ISSUE TITLE
A more feature needed for IINA

### ISSUE THREAD

**Issue by ScottChiang0627** [lhc70000/iina#1130] opened 2017-10-18 13:42 UTC
INNA is a quite powerful video player now. If one more feature could be added, I think INNA would be perfect. 

That is **bookmark function**, which let users jump to the bookmark quickly(by hotkey). And the function should include a bookmark creation feature, as well.

Hope this information to be helpful. 
: )

**Comment by alejx** [comment] 2018-01-02 23:12
Duplicate of #681.

**Closed by alejx** 2018-01-02 23:12 UTC
Labels: other: duplicate, type: feature request
