### ISSUE TITLE
IINA crashes when opening empty URL in Open URL dialog

### ISSUE THREAD

**Issue by sevenfourk** [lhc70000/iina#836] opened 2017-07-12 21:34 UTC
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**
IINA should throw some dialog alerting user to fill up valid url or something. Or whatever action, we may discuss here in this thread.

**Actual behavior:**
IINA Crashes

**Steps to reproduce:**
* open IINA
* open "Open URL" dialog
* Clock 'OK' or just press [Enter]
* IINA Crashes

**Comment by saagarjha** [comment] 2017-07-12 21:36
Duplicate of #830.

**Closed by saagarjha** 2017-07-12 21:36 UTC
