### ISSUE TITLE
YouTube playlist support is missing.

### ISSUE THREAD

**Issue by realsrikar** [lhc70000/iina#984] opened 2017-08-22 18:48 UTC
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**
When I open a video from YouTube which is on a playlist and hit the extension I expected it to automatically recognize that the video was in a playlist and to fetch the upcoming videos to the in-app playlist. All YouTube videos have a `?list=` at the end.

**Actual behavior:**
The app just plays the current video.

**Steps to reproduce:**
Open a playlist from YouTube

**How often does this happen?**
Whenever I try to open a YouTube playlist

**Comment by saagarjha** [comment] 2017-08-22 20:09
Duplicate of #774.

**Closed by saagarjha** 2017-08-22 20:09 UTC
