### ISSUE TITLE
Change the position of video preview on Touch Bar

### ISSUE THREAD

**Issue by Evilsine** [lhc70000/iina#1002] opened 2017-08-30 20:10 UTC
**System and IINA version:**

- macOS 10.12.6
- IINA 0.0.12

**Expected behavior:**
The current position of video preview on Touch Bar is covered by finger when adjusting playback slider. It would be much easier to see if the preview is on the left or right side of current position.

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by saagarjha** [comment] 2017-08-30 20:12
> covered by finger

I can't see this being an issue unless you're using a touchscreen…how is this occurring?

**Comment by ErikMinekus** [comment] 2018-07-01 08:53
Duplicate of #1294.

**Closed** 2018-07-01 09:16 UTC
