### ISSUE TITLE
Resize the playlist

### ISSUE THREAD

**Issue by troyliu0105** [lhc70000/iina#299] opened 2017-01-30 19:11 UTC
When file name is too long, it's hard to read in playlist...
adding resizing playlist's width feature may help... 😃

**Comment by inflation** [comment] 2017-01-30 21:49
You can try to hover over the item, it will give you the full name.

**Comment by saagarjha** [comment] 2017-01-31 00:20
This appears to be a duplicate of #253.

**Comment by troyliu0105** [comment] 2017-01-31 04:08
@inflation hovering doesn't help... 😭 , nothing appears
my platform: 10.12.3
iina version: 0.0.4

**Comment by troyliu0105** [comment] 2017-01-31 04:12
i see, those commits may be merged in next version... they havent be merged yet, so it still doesn't work now...

**Closed** 2017-02-04 08:42 UTC
Labels: duplicate
