### ISSUE TITLE
Equalizer setting not saved

### ISSUE THREAD

**Issue by GHubbler** [lhc70000/iina#929] opened 2017-07-29 22:07 UTC
After setting the equalizer it will loose all settings after quitting iina. When reopening iina, all equalizer settings are reset to flat.

Under Audio -> Audio filter there is an entry with #0 and eq settings listed. Even so this is also mostly not saved after quitting iina, nor is it possible to add or recall an audio filter setting. 

- macOS 10.12.6
- IINA 0.0.12

**Expected behavior:**
iina should alway remember the last EQ setting. Better it should have a working preset managment and default EQ setting.

**Comment by lhc70000** [comment] 2017-07-31 15:55
Duplicate of #525

**Comment by GHubbler** [comment] 2017-10-17 20:07
There is a little improvement as current EQ setting is now remembered per movie, but still not possible to use this setting globally for all movies. Unfortunately, there is still no preset or default setting of the EQ possible. Maybe there are similarities to #1109.

EQ setting is actually saved only per media file in:
~/Library/Application Support/com.colliderli.iina/watch_later/B0064078A182E701AC05A2D7AC8CFA29

The filename B0064078A182E701AC05A2D7AC8CFA29 is referenced in
~/Library/Application Support/com.colliderli.iina/history.plist

Tested with new iina 0.0.14 Build 45 on macOS 10.12.6.

**Closed** 2018-09-12 05:47 UTC
Labels: other: duplicate
