### ISSUE TITLE
Add 'playlist behavior' to Preferences

### ISSUE THREAD

**Issue by silic0ns0ul** [lhc70000/iina#194] opened 2017-01-17 06:34 UTC
Currently, the app seems to auto-create and auto-load a playlist when a) a media file is "double clicked" to playback from Finder, and b) when media file is opened via the File, Open menu. The created playlist is usually just all the media files found in the same current directory. And since there's a playlist, instead of ending playback of the current media file when the file is done and waiting for user input, the default behavior is to begin playing the next file in the playlist. I personally do not like this. I expect the app to open and play the one file I told it to, not create a playlist and play files one after the other. It would be great to have some 'playlist behavior' options in the Preferences. Thanks.

**Comment by megadr01d** [comment] 2017-01-17 15:50
Duplicate of https://github.com/lhc70000/iina/issues/72. However, the default should be to load all files in the folder, like an image viewer or audio player. Useful for series with multiple episodes but I guess an option won't hurt.

**Comment by dreamerblue** [comment] 2017-01-18 06:15
So do I.

Adding 2 options below may be better:
1. enable/disable auto play next
2. enable/disable auto create playlist

**Comment by schriftgestalt** [comment] 2017-01-18 12:56
I was hating the playlist behavior in other players. I would pledge for no automatic playlist whatsoever (not even a Preference). There are so many ways to create list. Selecting all files before opening, dragging the folder on the app icon...

**Closed** 2017-02-13 17:51 UTC
Labels: enhancement
