### ISSUE TITLE
option to have settings show in a floating window instead of panel

### ISSUE THREAD

**Issue by negativeions** [lhc70000/iina#1006] opened 2017-09-03 08:16 UTC
- macOS 10.12.6
- IINA 0.0.12

In some cases it would be more helpful to have a separate floating window for settings/AV controls instead of a pullout panel... as per this comment:
https://www.reddit.com/r/apple/comments/6ls4hs/vlc_alternative_iina_is_so_much_better_try_it_out/djwfbyp/

**Comment by saagarjha** [comment] 2017-09-03 18:35
Duplicate of #809.

**Closed by saagarjha** 2017-09-03 18:35 UTC
