### ISSUE TITLE
Can not change input source by press <caps lock> when iina is workding

### ISSUE THREAD

**Issue by cbdyzj** [lhc70000/iina#615] opened 2017-05-03 12:07 UTC
**System and IINA version:**

- macOS 10.12.4
- IINA 0.0.7

**Expected behavior:**

**Actual behavior:**

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by megadr01d** [comment] 2017-05-03 12:48
Dupe of https://github.com/lhc70000/iina/issues/132 and https://github.com/lhc70000/iina/issues/477.

**Comment by alejx** [comment] 2017-05-03 14:43
See #477 .

**Closed by alejx** 2017-05-03 14:44 UTC
Labels: duplicate
