### ISSUE TITLE
Control bar returns to default position after going to the next video.

### ISSUE THREAD

**Issue by goodman-capu** [lhc70000/iina#538] opened 2017-03-29 15:02 UTC
**System and IINA version:**

- macOS 10.12.4
- IINA 0.0.7

**Expected behavior:**
Control bar remains in the adjusted position after going to the next video.

**Actual behavior:**
Control bar returns to default position after going to the next video.

**Steps to reproduce:**
* Play a video
* Adjust the position of the control bar
* Press ⏩ to go to the next video

**How often does this happen?**
Every time

**Comment by megadr01d** [comment] 2017-03-29 16:00
Dupe of https://github.com/lhc70000/iina/issues/347 and https://github.com/lhc70000/iina/issues/466.

**Comment by goodman-capu** [comment] 2017-04-02 01:25
It's not strictly the same issue... I don't need to resize the window to trigger it.

**Comment by megadr01d** [comment] 2017-04-02 13:10
@goodman-capu You're right but I just wanted to link to all related issues so it's easier for the devs to close them when fixed. Besides, they all share the same problem: the control bar position should be saved/remembered (preferably, even between launches).

**Closed** 2017-06-03 14:11 UTC
Labels: feature: ui/ux, other: duplicate, progress: fixed in develop
