### ISSUE TITLE
 CPU occupancy is too high

### ISSUE THREAD

**Issue by HelloHeym** [lhc70000/iina#51] opened 2017-01-06 08:06 UTC
cpu 占用过高 硬件加速是否起作用了？？

**Comment by lhc70000** [comment] 2017-01-06 08:18
目前找到不少导致 CPU 高占用的问题，下个版本会解决一部分。

如果你觉得硬件加速没起作用，请检查一下 mpv log。

---

It can be caused by multiple problems. We have figured out some of them, and will update in next version.

Please check the mpv log if you doubt whether hwdec is enabled.

**Comment by znoodl** [comment] 2017-01-07 04:50
@lhc70000 直接打开文件播放没问题，如果通过播放列表打开CPU会负载过高

**Comment by lhc70000** [comment] 2017-01-12 17:21
All discovered problems should have been fixed in [v0.0.2](https://github.com/lhc70000/iina/releases/tag/v0.0.2).

If similar problem is still persistent, please test the media with mpv to make sure that it's not about mpv and decoding.

**Comment by lhc70000** [comment] 2017-01-30 13:16
0.0.4 _should_ fixed high CPU usage problem. Please test if there's any improvement.

If the problem persists, please reopen this issue.

**Closed by lhc70000** 2017-01-30 13:16 UTC
Labels: enhancement
