### ISSUE TITLE
ESC does not exit legacy full screen

### ISSUE THREAD

**Issue by JohnClay** [lhc70000/iina#1107] opened 2017-10-15 18:40 UTC
**System and IINA version:**

- macOS 10.13
- IINA 0.0.13

**Expected behavior:**
When set as a keyboard shortcut, ESC should be able to exit legacy full screen

**Actual behavior:**
When set as a keyboard shortcut, you cannot exit legacy full screen by pressing ESC.

**How often does this happen?**
Always

**Comment by lhc70000** [comment] 2017-10-15 18:44
It's a known issue, seems like a system constrain so we need to do more research.

**Comment by alejx** [comment] 2018-01-09 03:20
Duplicate of #1107.

**Comment by prohtex** [comment] 2018-01-11 12:43
Seems like this still exists in .15 build 60

**Comment by lhc70000** [comment] 2018-01-11 12:45
@prohtex build 60 doesn't contain this fix, but the next version will. It'll be released in several days.

**Closed** 2018-01-13 06:11 UTC
Labels: bug: general, feature: window, progress: fixed/implemented
