### ISSUE TITLE
mac os 10.14 mojave 

### ISSUE THREAD

**Issue by px123zx** [lhc70000/iina#1826] opened 2018-07-09 13:52 UTC
**System and IINA version:**

- macOS 10.13.4
- IINA 0.0.15.1

**Expected behavior:**
select close Btn. when close to the button, The status bar has been closed. It must be quick to click on success

**Comment by alejx** [comment] 2018-07-09 14:01
Duplicate of #1779.

**Closed by alejx** 2018-07-09 14:01 UTC
Labels: other: duplicate
