### ISSUE TITLE
Always float on top while playing seems not working|播放时置顶无效

### ISSUE THREAD

**Issue by xjkdev** [lhc70000/iina#533] opened 2017-03-29 01:38 UTC
macOS 10.12.4
IINA 0.0.7

"Always float on top while playing" is never work since i used this player, or maybe i have a misunderstanding of this option?
播放时置顶似乎从未生效过，我的理解是播放时，窗口置顶的选项打开，也就是类似画中画的效果，然而我还是必须手动打开窗口置顶才能让窗口置顶，而且这样的话暂停它也不会取消置顶。

**Comment by alejx** [comment] 2017-03-29 01:43
You are right. That should work.

**Comment by lhc70000** [comment] 2017-03-29 02:22
Sorry but I can't reproduce.

BTW canceling floating on top when paused is not implemented yet.

**Comment by lhc70000** [comment] 2017-03-29 03:10
This option only works for **all windows opened later** and will set all of them float on top, i.e. IINA's window will be on top permanently.

`Video > Float on Top` (Option+Cmd+T): Toggle floating on top
`This option`: Set floating on top for all windows opened later

It should be better to make it take effect immediately. @alejx will handle this.

**Comment by saagarjha** [comment] 2017-03-29 03:38
@xjkdev We also have Picture in Picture support, if that helps!

**Comment by alejx** [comment] 2017-05-04 05:03
Fixed in 0.0.8.

**Closed by alejx** 2017-05-04 05:03 UTC
Labels: enhancement, fixed in develop
