### ISSUE TITLE
Using Caps Lock to change input method failed when iina is in background

### ISSUE THREAD

**Issue by hguandl** [lhc70000/iina#768] opened 2017-06-22 16:03 UTC
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**

On macOS Sierra there's a function that allow users to press Caps Lock to switch input method between ABC and PinYin. 

**Actual behavior:**
When iina is in background, this function doesn't work. If I quit iina or focus on it, the function works as usual. 

**How often does this happen?**
I have found this issue since at least IINA 0.0.8.

**Comment by alejx** [comment] 2017-06-23 09:05
Duplicate of #477.

**Closed by alejx** 2017-06-23 09:05 UTC
Labels: other: duplicate
