### ISSUE TITLE
Subtitle chaos with ASS style rendering | ASS 中文字幕渲染乱码

### ISSUE THREAD

**Issue by kchen0x** [lhc70000/iina#499] opened 2017-03-17 04:33 UTC
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6

**Expected behavior:**

This is the correct subtitle, with `Ignore ASS styles` checked.

![](https://ww2.sinaimg.cn/large/006tNbRwgy1fdpq5ivy0vj315s0pgwix.jpg)

**Actual behavior:**

But when I want to use the ASS style, it turns out to be: (happens several times. )

![](https://ww4.sinaimg.cn/large/006tNbRwgy1fdpq4wn9zqj315s0pgaem.jpg)

This subtitle can be found here: http://subhd.com/ar/361322

(N/A for feature requests)

- Crash report:

- MPV log:

**Steps to reproduce:**

(N/A for feature requests)

- [ ] MPV does not have this problem.

**How often does this happen?**

(N/A for feature requests)

**Comment by saagarjha** [comment] 2017-03-17 04:35
Possible duplicate of #436?

**Comment by quentin-chen** [comment] 2017-03-17 04:43
@saagarjha Yes, maybe the same, it seems IINA choose `STKaiti` as default when what ASS assigning cannot be found. And the rendering with `STKaiti` has some problem in IINA.

I checked the  `Ignore ASS styles` box and choose `STKaiti`, the subtitle shows incorrectly as #436.

**Closed** 2018-09-12 05:47 UTC
Labels: other: duplicate
