### ISSUE TITLE
Touchbar slider is not updating in Music Mode

### ISSUE THREAD

**Issue by DV1X3R** [lhc70000/iina#1422] opened 2018-01-25 15:47 UTC
- Macbook Pro 2017
- macOS 10.13.2
- IINA 0.0.15

When playing music in music mode slider is not updating current position.
Everything works properly in the video mode.

![screen shot 2018-01-25 at 5 40 41 pm](https://user-images.githubusercontent.com/31878959/35397023-fe8c68de-01f6-11e8-9122-80a66cdcbd24.png)
<img width="1085" alt="touch bar shot 2018-01-25 at 5 40 14 pm" src="https://user-images.githubusercontent.com/31878959/35397025-feaaa1dc-01f6-11e8-917f-676eace977bf.png">

**Comment by ErikMinekus** [comment] 2018-01-26 19:53
Duplicate of #1369. And the playtime in the Touch Bar isn't updated either, I don't think 7c51b23 fixes that.

**Comment by lhc70000** [comment] 2018-01-27 11:18
@ErikMinekus Thanks, fixed.

**Closed** 2018-05-03 22:42 UTC
Labels: other: duplicate, progress: fixed/implemented
