### ISSUE TITLE
Don't hijack media keys when IINA is open but not playing

### ISSUE THREAD

**Issue by robmathers** [lhc70000/iina#778] opened 2017-06-27 16:24 UTC
## Summary
When IINA is open in the background (but no media is open), it prevents the standard media keys (found on Apple keyboards and others) from being used in other applications (like iTunes).

**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**
With IINA open in the background (with no media open), media keys should be able to control other applications (like iTunes). This is long standing standard Mac behaviour, as exhibited by apps like iTunes and QuickTime Player. It's common to leave Mac apps running but with no open windows; users shouldn't have to quit IINA just to get their media keys back.

If two media player apps are open, the order for control should be:
1. App in the foreground
2. App actively playing media
3. App most recently in the foreground

**Actual behavior:**
When IINA is open, it blocks all other apps from using the media keys. This happens even when IINA has no files open, and is in the background.

**Steps to reproduce:**
1. Open IINA (do not open a media file).
2. Open iTunes and start playing a song.
3. Press the play/pause button.
iTunes should pause, but doesn't.

iTunes *should* pause the song, especially when it is in the foreground.

- [x] MPV does not have this problem.

**How often does this happen?**
Every time IINA is open.

**Comment by lhc70000** [comment] 2017-07-15 03:57
It will be solved in macOS 10.13.

**Comment by davidpasztor** [comment] 2017-08-13 15:03
@lhc70000 is this issue planned to be solved for macOS 10.12? I just switched from MPlayerX to IINA for several reasons, but this is a really big issue for me, so if it won't be fixed for months, I guess I'll have to switch back to MPlayerX for the moment, since that doesn't hijack media controls.

**Comment by lhc70000** [comment] 2017-08-13 15:06
10.13 will be out soon in September. Are you planning to stay at 10.12 then?

**Comment by davidpasztor** [comment] 2017-08-13 15:10
There is no guarantee that 10.13 will be out in September and considering the bugs that usually new macOS versions have, I don't plan on updating for a while, until 10.13 becomes stable enough. Moreover, quite a few people might not be updating to 10.13 at all and there is a working solution for 10.12 as well, quite a few other media players are already achieving this functionality, so this feels like a regression compared to those.

**Closed** 2018-01-13 06:11 UTC
Labels: progress: fixed/implemented, type: enhancement

**Comment by davidpasztor** [comment] 2018-01-13 16:11
@alejx @lhc70000 I have just updated to 0.0.15 build 62, but the issue still persists on macOS 10.12.5. Wasn't #1063 supposed to fix this issue on earlier versions of macOS than 10.13 as well? If not, I ask you to reopen this issue, since the problem still persists.
