### ISSUE TITLE
Choose the Resolution on Youtube

### ISSUE THREAD

**Issue by Kontor23** [lhc70000/iina#1583] opened 2018-03-26 20:22 UTC
Hi,

it would be great if there is a way in iina to choose the resolution of the youtube stream. Till now it chooses always the best possible quality. Thank you very much

Greetings
Kontor23

**Comment by lhc70000** [comment] 2018-03-28 16:38
This should be a duplicate of #1432.

**Closed by lhc70000** 2018-03-28 16:38 UTC
Labels: other: duplicate
