### ISSUE TITLE
Buggy audio device selection

### ISSUE THREAD

**Issue by Lord-Kamina** [lhc70000/iina#1795] opened 2018-06-18 16:21 UTC
**System and IINA version:**

- macOS 10.13.5
- IINA 1.0.0-beta2

**Expected behavior:**

Correct selection of audio output device.

**Actual behavior:**

I am using a 2017 MBP with Touch bar. I've got a CalDigit TS3 plus (which features audio connectors as well as a display port, which are connected to nothing.)

And I'm additionally using a USB-C to HDMI cable to connect to my TV. Whenever I open 
IINA, I have to manually select the Audio Device because it resets to auto and auto apparently prefers the CalDigit Thunderbolt audio, even though it's not actually connected to anything.

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by alejx** [comment] 2018-06-18 16:59
Duplicate of #1593.

**Closed** 2018-06-19 07:28 UTC
Labels: other: duplicate, type: enhancement
