### ISSUE TITLE
Homebrew Installation not working

### ISSUE THREAD

**Issue by danshao** [lhc70000/iina#543] opened 2017-03-30 15:36 UTC
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.7

**Expected behavior:**

`brew install cask iina` actually installs IINA via homebrew. 

Reference: Issue #440 

**Actual behavior:**

No such formula for homebrew.

- Crash report:
```
$ brew cask install iina
Error: No available Cask for iina
Error: nothing to install


$ brew install iina
Error: No available formula with the name "iina"
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
This formula was found in a tap:
Caskroom/cask/iina
To install it, run:
  brew install Caskroom/cask/iina


$ brew install Caskroom/cask/iina
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
media-info                                                               mediaconch

==> brew cask install Caskroom/cask/iina
Error: Tap caskroom/cask already tapped.

Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Homebrew/Library/Homebrew/tap.rb:196:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source/untapped_qualified.rb:9:in `me?'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source.rb:28:in `block in for_query'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source.rb:26:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source.rb:26:in `find'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source.rb:26:in `for_query'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc.rb:56:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:21:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:101:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:144:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

**Comment by saagarjha** [comment] 2017-03-30 16:28
I can't reproduce this; could you run `brew cask search iina` and post the results here?

**Comment by danshao** [comment] 2017-03-30 16:32
Nevermind, resolved.

Thought `brew upgrade` was replacing `brew update` and `brew upgrade -all`. Turns out `brew update` is still necessary.

**Comment by saagarjha** [comment] 2017-03-30 16:34
Alright, I'll close this as resolved then.

**Closed by saagarjha** 2017-03-30 16:34 UTC
