### ISSUE TITLE
IINA Blocks macOS system Sleep processing

### ISSUE THREAD

**Issue by tywtyw2002** [lhc70000/iina#556] opened 2017-04-03 21:01 UTC
If app IINA is open whether with video in pause mode or without video, its will block the osx sleep process.

by use command `pmset -g assertions` to get the information about which block the system sleep get follow results. The IINA app did not play any video or in pause mode.

```
2017-04-03 14:53:55 -0600
Assertion status system-wide:
   BackgroundTask                 0
   ApplePushServiceTask           0
   UserIsActive                   1
   PreventUserIdleDisplaySleep    1
   PreventSystemSleep             0
   ExternalMedia                  0
   PreventUserIdleSystemSleep     1
   NetworkClientActive            0
Listed by owning process:
   pid 73465(IINA): [0x00022c6200059849] 38:20:38 NoDisplaySleepAssertion named: "IINA is playing video"
   pid 375(useractivityd): [0x0002a2e50001a3f9] 00:00:02 PreventUserIdleSystemSleep named: "BTLEAdvertisement"
   pid 117(hidd): [0x0002a2670009a3f2] 00:02:07 UserIsActive named: "com.apple.iohideventsystem.queue.tickle.4294993511.11"
	Timeout will fire in 178 secs Action=TimeoutActionRelease
   pid 211(coreaudiod): [0x00029a9800019af9] 00:35:25 PreventUserIdleSystemSleep named: "com.apple.audio.AppleHDAEngineOutput:1B,0,1,1:0.context.preventuseridlesleep"
	Created for PID: 73931.
   pid 291(Google Chrome): [0x0000d84900019976] 95:53:43 NoIdleSleepAssertion named: "WebRTC has active PeerConnections"
Kernel Assertions: 0x100=MAGICWAKE
   id=505  level=255 0x100=MAGICWAKE mod=4/2/17, 21:38  description=en0 owner=en0
Idle sleep preventers: IODisplayWrangle
```

The IINA should only block system sleep while it is playing video, otherwise should release the blocking.

**Comment by alejx** [comment] 2017-04-04 04:46
Duplicated with #287 .
It should be fixed already. Did you upgrade to the latest version of IINA? I cannot reproduce this problem.

**Comment by quentin-chen** [comment] 2017-04-25 04:46
I have the same problem with latest version.

**Comment by quentin-chen** [comment] 2017-04-30 05:42
Movie paused, and blocked the system from sleep.

```
2017-04-29 22:40:57 -0700
Assertion status system-wide:
   BackgroundTask                 0
   ApplePushServiceTask           0
   UserIsActive                   1
   PreventUserIdleDisplaySleep    1
   PreventSystemSleep             0
   ExternalMedia                  0
   PreventUserIdleSystemSleep     1
   NetworkClientActive            0
Listed by owning process:
   pid 102(hidd): [0x0001c79200099841] 00:01:45 UserIsActive named: "com.apple.iohideventsystem.queue.tickle.4294968357.3"
	Timeout will fire in 177 secs Action=TimeoutActionRelease
   pid 283(useractivityd): [0x0001c7f90001985a] 00:00:02 PreventUserIdleSystemSleep named: "BTLEAdvertisement"
   pid 6451(IINA): [0x0001a35000059518] 02:36:26 NoDisplaySleepAssertion named: "IINA is playing video"
No kernel assertions.
Idle sleep preventers: IODisplayWrangler
```

**Comment by alejx** [comment] 2017-05-03 20:03
See #593. Please test on the latest version.

**Comment by tywtyw2002** [comment] 2017-05-25 02:03
No video play in IINA, but still this problem.

Version 0.0.9 Build 21


```
tyw@CosHiM-MAC:~|⇒  pmset -g assertions
2017-05-24 20:00:17 -0600
Assertion status system-wide:
   BackgroundTask                 0
   ApplePushServiceTask           0
   UserIsActive                   1
   PreventUserIdleDisplaySleep    1
   PreventSystemSleep             0
   ExternalMedia                  0
   PreventUserIdleSystemSleep     0
   NetworkClientActive            0
Listed by owning process:
   pid 1631(IINA): [0x00000c0c000582fd] 00:09:05 NoDisplaySleepAssertion named: "IINA is playing video"
   pid 119(hidd): [0x00000e0d00098318] 00:00:32 UserIsActive named: "com.apple.iohideventsystem.queue.tickle.4294968829.3"
	Timeout will fire in 178 secs Action=TimeoutActionRelease
Kernel Assertions: 0x100=MAGICWAKE
   id=505  level=255 0x100=MAGICWAKE mod=12/31/69, 17:00  description=en0 owner=en0
Idle sleep preventers: IODisplayWrangler
```

**Comment by tywtyw2002** [comment] 2017-05-25 02:27
I do not what is the exactly fully steps to repeat this problem, however, the follow steps will repeat the problem.

1. open IINA by alfred. 
2. Drag video from download folder(with Chinese filename.) to IINA in dock.
3. wait ~30s close it by click (X)
4. Open video from URL.
5. Open chrome, and IINA also float on top.
6. wait ~40s, move mouse to IINA and close it by CMD+W. Note: menu bar is Chrome's menu bar.
7. pmset -m assertions

**Comment by alejx** [comment] 2017-05-27 13:41
@tywtyw2002 Cause I cannot reproduce by your steps, can you try on the latest develop branch? Otherwise I can send you a latest copy.

**Comment by tywtyw2002** [comment] 2017-05-28 20:01
@alejx sure, please send me the copy. AT my github user_id @ gmail.com.

You also can put some log string for `Set sleep block flag` and `unset sleep block flag` in this version to help the debug.

**Comment by lhc70000** [comment] 2017-06-06 08:32
Any update on this issue?

**Comment by alejx** [comment] 2017-07-01 16:33
See bbb7a04a1856e59dd3238769b2b19d7bf9df0274

**Comment by mutedsignal** [comment] 2017-07-04 22:43
I am on the latest version, and can report it remains an issue:

`pmset -g assertions
2017-07-04 18:41:54 -0400
Assertion status system-wide:
   BackgroundTask                 0
   ApplePushServiceTask           0
   UserIsActive                   1
   PreventUserIdleDisplaySleep    1
   PreventSystemSleep             0
   ExternalMedia                  0
   PreventUserIdleSystemSleep     0
   NetworkClientActive            0
Listed by owning process:
   pid 2733(IINA): [0x0000732c00058329] 34:04:42 NoDisplaySleepAssertion named: "IINA is playing video"
   pid 116(hidd): [0x00015c0b00099b92] 05:13:43 UserIsActive named: "com.apple.iohideventsystem.queue.tickle.4294977285.3"
	Timeout will fire in 596 secs Action=TimeoutActionRelease
Kernel Assertions: 0x100=MAGICWAKE
   id=505  level=255 0x100=MAGICWAKE mod=7/4/17, 6:42 PM description=en0 owner=en0
Idle sleep preventers: IODisplayWrangler`

**Closed** 2017-07-17 07:08 UTC
Labels: bug: general, progress: fixed in develop
