### ISSUE TITLE
Settings reverting back to default

### ISSUE THREAD

**Issue by j4y4r1987** [lhc70000/iina#1049] opened 2017-09-26 22:38 UTC
- macOS 10.13
- IINA 0.0.12

Settings are reverting back to default every time a file is opened/played. This began after upgrading to High Sierra.

**Comment by doggles** [comment] 2017-09-28 09:51
Same OS, same app version, same issue. To add: the settings, for me, seem to revert back to defaults after a few minutes or so into the video, which I can tell has happened when I see the video stutter for a second or so.

**Comment by lhc70000** [comment] 2017-09-28 10:53
Please stay tuned. We are still trying to find the reason.

We got a user who reported the same problem on 10.12 back in September, so perhaps it has nothing to do with the system version. In that case, all settings were reverted to default at random time, and it never happened since upgrading to 10.13.

Here is the latest development build (build 40), you can firstly check if the problem still exists in this newer version: https://drive.google.com/open?id=0B7tEU25gz8nhWm14Nk5SVGZnOVE

If the problem persists and you can **reproduce it stably** even with the above build 40, I'd like to provide you some debug builds to collect more information.

@saagarjha, do you have any thoughts?

**Comment by doggles** [comment] 2017-09-28 16:12
@lhc70000 Not seeing this issue on build 40. However, just to note: there's an uncaught exception with CALayerGeometry if you have the _on media open enter fullscreen_ behavior enabled.

**Comment by lhc70000** [comment] 2017-09-29 07:37
@doggles Thanks, fixed in develop branch.

**Comment by saagarjha** [comment] 2017-09-30 07:45
Hmm…@doggles could you check the preferences file in `~/Library/Preferences/com.colliderli.iina.plist` before and after the issue occurs to see if there's a change?

**Comment by doggles** [comment] 2017-09-30 23:13
@saagarjha do you want me to create a new issue for this? 

[pre-crash plist](https://gist.github.com/doggles/4ff4915ef3af7a74192a8dc40df6dba1#file-iina-0-0-12-b40-com-colliderli-iina-plist-before)
[post-crash plist](https://gist.github.com/doggles/4ff4915ef3af7a74192a8dc40df6dba1#file-iina-0-0-12-b40-com-colliderli-iina-plist-crash)
[crash report](https://gist.github.com/doggles/4ff4915ef3af7a74192a8dc40df6dba1#file-iina-0-0-12-b40-crash-log)

**Comment by saagarjha** [comment] 2017-09-30 23:18
Oh, is this from the crash you were getting? I was looking for the preferences before and after you had the preferences get wiped.

**Comment by doggles** [comment] 2017-09-30 23:21
@saagarjha ah, gotcha. that appears to be [fixed](https://github.com/lhc70000/iina/issues/1049#issuecomment-332886564) in build 40, which introduced that new, unrelated crash.

**Comment by saagarjha** [comment] 2017-09-30 23:23
Yes, in that case I'd recommend making a new bug report with the full steps need to reproduce the issue. Thanks!

**Comment by ozguncagri** [comment] 2017-10-04 03:11
It was happened to me in the middle of the video. It was really interesting.

**Comment by cyberrave** [comment] 2017-10-06 05:26
Hey Guys,
I've been experiencing this too even on the 10.13.1 beta.  Just wanted to report a few observations:
Settings only appear to revert when using a mpv config file.
Settings appear to only revert when opening the settings window within iina.
If you quit the app the reverted settings are not saved (original settings are restored on app restart).

**Comment by TempSpas** [comment] 2017-10-10 12:44
I had this happen while a video was playing. I moused over the onscreen controller to move it, and instantly upon clicking it the controller went from Ultra Dark (my setting) to Dark (the default). Sure enough, all of the custom settings I had set were reset to the defaults.

Build 37
macOS 10.13

**Comment by TempSpas** [comment] 2017-10-16 23:05
Just had the issue happen on 0.0.13 build 42, so it looks like it either wasn't fixed in build 40, or it was but was broken again.

**Comment by babalooza** [comment] 2017-10-18 09:54
I can confirm TempSpas' experience, had it happen with 0.0.13 as well as with 0.0.14 build 47.
And it happens quite often, for every third or fourth movie IINA runs with default prefs. But my preference settings are not lost. If I quit IINA and open the same movie again, IINA reverts back to my settings. Sometimes I have to manually select my shortcut settings from the list though.

**Comment by babalooza** [comment] 2017-10-18 12:39
The hole issue might be a localization problem. I am running a German macOS and so IINA runs in German as well. A few hours back I have set IINA to always launch in English though and so far the settings didn't revert back to the default ones.
I will test that for the next couple of days and report back.

Meanwhile, all of you with this problem, are you running an English macOS or a localized one?

**Comment by TempSpas** [comment] 2017-10-18 17:04
I'm running an English macOS.

**Comment by Arve** [comment] 2017-10-19 15:14
Running on English MacOS here, and this only started showing up after MacOS 10.13 for me, with no updates to IINA.

**Comment by HansVanEijsden** [comment] 2017-10-19 17:44
Running Dutch macOS, High Sierra with IINA 0.0.14 build 47 - same problems (and a lot of `Invalid pointer dequeued from free list` crashes).

**Comment by babalooza** [comment] 2017-10-19 21:22
Ok, the localization idea doesn't hold up. Whether I am running IINA in German or English, the reverting back to defaults issue still happens. Also others on English systems encounter that issue.

And as well HansVanEijsden I encounter multiple crashes with the `Invalid pointer dequeued from free list` error running IINA 0.0.14 build 47 on macOS 10.13. Way more than with previous builds.

**Comment by wao1201** [comment] 2017-10-20 10:23
Got same issue.

System and IINA version:

macOS 10.13
IINA 0.0.14 build 47

**Comment by Arve** [comment] 2017-10-20 13:13
Well, there is no rhyme or reason to it:

It most often happens if you quit IINA before opening a new file - but not always, and there doesn't seem to be a particular pattern to it, other than it possibly happens more often when loading a different file.

When the bug happens, it most definitely happens _after_ the application has started, and the file you want to view has loaded:  I can see a flash of how I want to have IINA set up, before it suddenly forgets that the on-screen controller should be at bottom, and resets it to the default floating - so it seems to load the preferences, and then instantly get amnesia.

I've also seen it get stuck in some weird in-between state, where if I did the following when it reset:

1. Pause the movie
2. Go into preferences
3. Set prefs how I wanted them
4. Immediately quit

… IINA would remember my settings, but __only_ for that video file.  For other video files, it'd revert to default, and yet when I opened the same video file that was open during my "reset settings and quit" cycle, it would remember those settings.

**Comment by TempSpas** [comment] 2017-10-23 13:27
After reverting back to 0.0.12 to avoid the crashing issue, this settings issue went away. Kind of odd then that someone reported it happening on 0.0.12; had they just upgraded recently?

Also, the bug seems to temporarily remove the custom keybinding configuration option from the list in preferences. Mine is simply named "Custom," and when the bug would happen I would go into settings to select it, only to find that it wasn't in the dropdown. If I attempted to make a new config named "Custom," it would alert me that the name was already taken, at which point it would become available in the dropdown once again.

**Comment by TempSpas** [comment] 2017-10-24 13:47
Just had this happen for the first time ever on 0.0.12, so further confirmation that it's not tied to version.

**Comment by jerryjune** [comment] 2017-10-25 10:29
this issue is not resolved on latest version( 0.0.14.1 build 55)
but it happen randomly. sometimes it will roll back to default configuration, but if you close the application and open again, it recovery to my settings.

**Comment by KaiHD** [comment] 2017-10-26 02:56
I have the situation with @jerryjune above.

**Comment by hemedani** [comment] 2017-10-27 16:17
I have the same issue like @Arve

**Comment by emilianjung** [comment] 2017-11-05 12:00
Latest update still didn't resolve the issue for me. Only setting I change is the subtitles font size as the default one is massive. Even if I finish watching one episode of a TV show and go straight to another, the setting are back to default.

**Comment by unpin** [comment] 2017-11-08 15:15
same here, it has happened since 0.0.12.

**Comment by jerkstore369** [comment] 2017-11-08 15:57
IINA 0.14.1 b55
macOS Sierra 10.12.6

I can confirm that IINA reverts all settings back to default upon restart I think. Can't confirm it happens every time. Just noticed now, though, that all my keybindings are gone.

**Comment by mrrs555** [comment] 2017-11-20 03:22
Same issue, preference don’t save at all. 

macOS 10.13.1
IINA 0.0.14.1 Build55

**Comment by MartinZubek** [comment] 2017-12-29 12:05
Not sure what exactly has changed, but I no longer experience this problem. Maybe it was caused by some system problem which was fixed by one of latest system updates. Can anyone confirm this?

**Comment by lhc70000** [comment] 2017-12-29 12:08
@MartinZubek  Yes, it has been fixed in macOS 10.13.2 (and I forgot to close this issue).

source: https://twitter.com/Catfish_Man/status/938489343605276677

**Closed by lhc70000** 2017-12-29 12:08 UTC
Labels: bug: general, help wanted

**Comment by saagarjha** [comment] 2017-12-30 01:37
Ooh, a Foundation bug! Glad to see this is fixed. Looks like I had also been unwittingly affected by this bug in Mail.app. Guess I just don't use IINA enough.
