### ISSUE TITLE
High CPU temperature with iStat dropdown menu shown

### ISSUE THREAD

**Issue by Orz-PX** [lhc70000/iina#275] opened 2017-01-27 00:52 UTC
Update:
The case I described earlier is not fully correct. 

The actual case is:
During playback with IINA, I check the temperature from the iStat dropdown from the menubar. The temperature rises while the dropdown is shown, and when the it is closed, the temperature goes back to normal. 

I have also tested against playing via mpv from terminal, same symptom persists. 

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

The player costs very little cpu usage, which is good. 
However, the cpu cores' temperature rises rapidly to 90+ degrees, and forces fan to work to cool down. 
The issue is slightly improved when "hardware decoding" is unchecked, but the temperature is still significantly higher compared to VLC or Quicktime player. 

Enviroment:
MBP 13 retina, Late 2013 on macOS 10.12.3

**Comment by megadr01d** [comment] 2017-01-27 01:45
Probably duplicate of https://github.com/lhc70000/iina/issues/65.

**Comment by Orz-PX** [comment] 2017-01-27 02:05
Not quite, it's an interesting case I think. 
I have edited the issue to correctly illustrate the case.

**Comment by lhc70000** [comment] 2017-01-27 09:20
We _may_ change the rendering mechanism later in 0.0.5, which could solve energy consuming problem (also bring lots of other benefits, like possible to avoid requiring OpenGL 3.2).

@megadr01d Thank you very much for tracking issues in this project.

If you wanna have a try, please pull and build from `mpv_0_23_round2_calayer` branch.

**Comment by megadr01d** [comment] 2017-01-27 14:00
@lhc70000 No problem, my friend.

**Comment by lhc70000** [comment] 2017-01-30 13:14
0.0.4 _should_ fixed high CPU usage problem. Please test if there's any improvement.

If mpv also has the same problem, it should not be something IINA can do. Also, iStat itself does consume lots of CPU.

**Closed** 2017-06-04 01:49 UTC
Labels: bug: confirmation needed
