### ISSUE TITLE
Capslock to switch Korean IME isn't working while IINA is running. 

### ISSUE THREAD

**Issue by goodhyun** [lhc70000/iina#846] opened 2017-07-15 03:34 UTC
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.11

**Expected behavior:**

As of macOS 10.12, capslock key is used to switch Korean input method.

**Actual behavior:**

However, this functionality isn't working while IINA is running. 

- Crash report:
```

```

- MPV log:
```

```

**Steps to reproduce:**

- [x] MPV does not have this problem.

**How often does this happen?**

**Comment by lhc70000** [comment] 2017-07-15 03:37
Please turn off media key as a workaround. It'll be solved in 10.13.

Dupe of #477

**Closed** 2018-01-13 06:11 UTC
Labels: other: duplicate, progress: fixed/implemented
