### ISSUE TITLE
you-get support question

### ISSUE THREAD

**Issue by ChengLuffy** [lhc70000/iina#640] opened 2017-05-11 05:29 UTC
will iina support [you-get](https://github.com/soimort/you-get)?
because in China, you-get does better than youtube-dl,  such as Youku, Tencent video.

**Comment by megadr01d** [comment] 2017-05-11 16:26
Duplicate of https://github.com/lhc70000/iina/issues/58 and https://github.com/lhc70000/iina/issues/335.

**Closed** 2017-05-27 13:46 UTC
Labels: duplicate
