### ISSUE TITLE
Add a default empty window when launched

### ISSUE THREAD

**Issue by RyanWangGit** [lhc70000/iina#502] opened 2017-03-18 15:34 UTC
**System and IINA version:**

- macOS 10.12.3
- IINA 0.0.6

**Expected behavior:**

Traditional media player show an default empty window when launched without assigning a media file, as is shown below (`Movist`):

<img width="640" alt="Movist Screenshot" src="https://cloud.githubusercontent.com/assets/10323518/24073416/60849ea0-0c32-11e7-9f96-785b8464980e.png">

Which I believe is commonly accepted by users, thus it confused me when I first launched `IINA` as nothing showed up and I thought there is a failure during the launch.

**Comment by inflation** [comment] 2017-03-18 17:03
You can enable `Preference > General > Open a choose file panel after starting`.

**Comment by saagarjha** [comment] 2017-03-18 17:28
Possible duplicate of closed issue #174– @RyanWangGit are you fine with a file selector or do you need a player window at startup?

**Comment by RyanWangGit** [comment] 2017-03-18 17:52
@saagarjha Oops, sorry. I didn't find it in the first place. I still think that a so-called "Welcome Panel" is needed for best user experience as most of my applications have (or maybe they have?) Hope you can consider adding it in future releases?

**Comment by saagarjha** [comment] 2017-03-18 17:53
We might consider adding one for the first launch; but IMO they can quickly get in the way.

**Comment by alejx** [comment] 2017-03-18 18:13
I'd like to make opening the open penal by default, so that user will not confused at whether IINA is launched or not.

**Comment by lhc70000** [comment] 2017-03-18 18:47
The reason why I didn't add a initial window is simple: _On my computer_, Both QuickTime and MplayerX doesn't show anything at launch, so I _thought_ it's a common design on macOS. However, I heard that most of others' QuickTime show a file choose panel when started, and even one when clicked Dock. (Is there any user defaults controlling this behavior?)

**Comment by lhc70000** [comment] 2017-03-18 18:49
BTW certainly I'll add a welcome window and set it as default before beta release.

**Comment by saagarjha** [comment] 2017-03-18 19:48
If you're looking for ideas, take a look at iWork's behavior:

1st launch: Welcome window that shows off its features
Subsequent launches: System open dialog

**Closed** 2017-03-19 02:09 UTC
Labels: duplicate
