### ISSUE TITLE
Can't close player window on Mojave 10.14

### ISSUE THREAD

**Issue by prohtex** [lhc70000/iina#1824] opened 2018-07-08 19:23 UTC
On Mac OS 10.14 Mojave (Public Beta 2), moving the cursor to the upper left corner of the player window makes the window controls (Red/Yellow/Green buttons) disappear, making it impossible to close the player window with the mouse.

**Comment by ErikMinekus** [comment] 2018-07-08 20:56
Duplicate of #1779.

**Closed** 2018-07-08 20:58 UTC
