### ISSUE TITLE
0.0.4 crashes on launch

### ISSUE THREAD

**Issue by shila77** [lhc70000/iina#300] opened 2017-01-30 22:10 UTC

**Comment by lowercaseman** [comment] 2017-01-30 22:17
Can confirm. Running macOS 10.2.4 beta 1 (16E144f)
Can provide logs

**Comment by inflation** [comment] 2017-01-30 23:37
@lowercaseman Any logs are appreciated.

**Comment by lowercaseman** [comment] 2017-01-30 23:56
[iina.4.macOS12.2.4.beta.1.lowercaseguy.logs.txt](https://github.com/lhc70000/iina/files/740792/iina.4.macOS12.2.4.beta.1.lowercaseguy.logs.txt)

**Comment by inflation** [comment] 2017-01-31 01:14
I believe this problem is caused because the `libvapoursynth.dylib` is not compiled to support the beta system. But I can't reproduce in my environment. Maybe we can exclude this library until we figure out what's going wrong? @lhc70000

**Comment by shila77** [comment] 2017-01-31 07:29
I'm not using the beta. Crashes also on 12.2.4. No problem running 0.0.3.

**Comment by lhc70000** [comment] 2017-01-31 08:59
I compiled a binary without `vapoursynth` and replaced current release with the fixed one.

Please download from release again and have a test.

([direct link](https://github.com/lhc70000/iina/releases/download/v0.0.4/IINA.v0.0.4.zip))

**Comment by megadr01d** [comment] 2017-01-31 11:05
> I compiled a binary without vapoursynth and replaced current release with the fixed one.

0.0.4 also crashes on launch for me (without opening a movie), on OS X 10.11.6 El Capitan. Previous versions crashed when opening movies only. Will try the updated binary when I get home and report back.

**Comment by shila77** [comment] 2017-01-31 20:49
0.0.4 build 7 working fine

**Comment by megadr01d** [comment] 2017-01-31 23:16
@lhc70000 Great work! Not only 0.0.4b7 is launching correctly but also opens movies just fine without crashing for the first time, on my system. Somehow it fixed issue https://github.com/lhc70000/iina/issues/171 so closing that one.

**Comment by lhc70000** [comment] 2017-02-02 09:47
Does the new binary work?

**Comment by megadr01d** [comment] 2017-02-02 10:26
> Does the new binary work?

We said "yes"!

**Comment by lhc70000** [comment] 2017-02-02 13:52
@megadr01d  lol nice

**Closed by lhc70000** 2017-02-02 13:52 UTC
