### ISSUE TITLE
macOS 10.12.6, Xcode 9A235, git 76c4d38: run fails with EXC_BAD_INSTRUCTION

### ISSUE THREAD

**Issue by Kadigan** [lhc70000/iina#1099] opened 2017-10-12 22:13 UTC
**System and IINA version:**

- macOS: 10.12.6
- IINA: git clone of 76c4d38 (latest at the time of this report)

**Expected behavior:**

IINA builds and runs.

**Actual behavior:**

IINA run drops into debugger.

- Crash report:
```
see attached screenshot
```
**Steps to reproduce:**

Following step-by-step at https://github.com/lhc70000/iina/wiki/Build-the-Project

1) install Xcode 9A235
2) "sudo gem install cocoapods"
3) "git clone https://github.com/lhc70000/iina.git"
4) cd into iina
5) "pod install"
6) open iina.xcworkspace
7) click "Run"
8) build is successful
9) run interrupts with Thread 1: EXC_BAD_INSTRUCTION

**How often does this happen?**

I have been unable to successfully run IINA by building it via Xcode.

![2017-10-13 00_09_54-studio - vnc viewer](https://user-images.githubusercontent.com/16637976/31521751-fa9fe3ac-afaa-11e7-99f8-d44b35c5f635.png)

**Comment by inflation** [comment] 2017-10-12 22:20
Can you provide more details about the crash? The single screenshot is not very informative. Thank you.

**Comment by Kadigan** [comment] 2017-10-12 22:21
I'm unfortunately not that familiar with Xcode. Can you please tell me how to gather the most useful info for you?

**Comment by inflation** [comment] 2017-10-12 22:33
You could check 'Runtime' under 'Issue Navigator'.

**Comment by Kadigan** [comment] 2017-10-12 22:36
It states "No Runtime Issues".

**Comment by saagarjha** [comment] 2017-10-12 22:38
In your screenshot, there's a button in the bottom left in the text field that looks like a box "sandwich". Please click and send another screenshot that as it will provide a more detailed stack trace.

**Comment by Kadigan** [comment] 2017-10-12 22:40
![2017-10-13 00_40_29-studio - vnc viewer](https://user-images.githubusercontent.com/16637976/31522635-257fe726-afaf-11e7-95a3-d61d2a6b09d2.png)

**Comment by saagarjha** [comment] 2017-10-12 22:42
Thanks. Could you also see if this issue reproduces without a debugger attached? There should be a copy of IINA.app in the file navigator sidebar under the "Products" folder; try running that manually and seeing if it also crashes. If so, please attach the crash log here.

**Comment by Kadigan** [comment] 2017-10-12 22:51
The issue also reproduces when I launch IINA.app under Products/Debug.

"Problem Details and System Configuration" contents attached.
[2017-10-13, 00-47, IINA debug dump.txt](https://github.com/lhc70000/iina/files/1380936/2017-10-13.00-47.IINA.debug.dump.txt)


Crash report attached.
[2017-10-13, 00-47, IINA crash report.txt](https://github.com/lhc70000/iina/files/1380946/2017-10-13.00-47.IINA.crash.report.txt)

**Comment by inflation** [comment] 2017-10-12 22:58
This seems to be an error in the precompiled `glib`. 

Do you have mpv installed and does it work? If so, you could try to compile IINA with your working mpv libraries.

**Comment by Kadigan** [comment] 2017-10-12 23:10
I have mpv installed and it does indeed work (I installed it from the guide on using IINA with SVP). I have removed ```libmpv.1.25.0.dylib```, ```libmpv.1.dylib``` and ```libmpv.dylib``` from ```Products/Debug/IINA.app/Contents/Frameworks/``` and now it launches.

I seem to have assumed incorrectly as to which mpv will work w/ IINA (I assumed there was one bundled w/ the project for internal use). I have now followed the instructions on git's main page, namely running ```parse_doc.rb``` and ```change_lib_dependencies.rb``` -- and it now builds and launches correctly.

I assume this is User Error. Can the instructions be amended to reflect that the build will fail if you happen to have your own mpv and fail to update IINA's references?

**Comment by inflation** [comment] 2017-10-13 15:42
I'm assuming you are building on `master` branch, which is shipping a very old precompiled `mpv` library. Try to checkout `develop` branch and see if it could build. This will help us to determine if it has been solved by new version of the library. Thank you.

**Comment by lhc70000** [comment] 2017-10-24 18:19
Fixed in 0.0.14.1.

**Closed by lhc70000** 2017-10-24 18:19 UTC
Labels: type: question

**Comment by Kadigan** [comment] 2018-05-08 18:00
I apologize for not coming back to this sooner - I failed to notice there was a follow-up comment. In any case, I'm glad it's been fixed, though I fully expected this to be _my own ignorance_. :-)

**Comment by saagarjha** [comment] 2018-05-08 21:04
Actually, this hasn't been fixed: #1660. We know what this issue is now, though!
