### ISSUE TITLE
Delete Current File

### ISSUE THREAD

**Issue by open1010** [lhc70000/iina#1131] opened 2017-10-18 14:16 UTC
hello,

IINA 0.0.14

I am confusing in the Menu

FILE \"Delete Current File"

is it acutally means "Close Current File"

thanks

**Comment by lhc70000** [comment] 2017-10-18 14:18
@open1010 No, it's putting the file into trash.

**Comment by open1010** [comment] 2017-10-18 14:28
I think it is a very dangerous feature, somethings it may accidentally delete the file escpecially the files are stored in the network drive. The deleted files cannot be recovered. 

may I suggest, there is an option in the preferences settings user can disable this feature. 

thanks

**Comment by lhc70000** [comment] 2017-10-18 14:40
- It's not assigned to any key shortcut.
- It only trashes the file, so you can always put it back even clicked the menu item accidentally.
- I never tested it with remote files, but I think macOS won't delete files permanently. Have you tried it and confirmed that the deleted file can't be restored?

**Comment by JohnClay** [comment] 2017-10-18 20:26
@lhc70000 With network storage, any files are deleted immediately unless the storage server has a trash system setup. Most don't. This includes Finder operations, though it does warn the user.

I just tested, and IINA does *not* permanently delete the file. Instead, it informs the user that the file cannot be deleted.
![screen shot 2017-10-18 at 4 25 25 pm](https://user-images.githubusercontent.com/627077/31741038-0178fdf6-b421-11e7-9a51-3b7e202d4162.png)

**Comment by lhc70000** [comment] 2017-10-24 18:29
@open1010 Do you still have any question now?

**Comment by Toontje** [comment] 2018-02-25 17:41
Yes, can you assign a keyboard shortcut to it?

**Comment by JefferyLay** [comment] 2018-08-08 17:29
I've assigned a key to delete the current file, as I'm going through a large media hoard sorting which files to keep. However, because the files I'm going through are on a network server, I get the same error message as JohnClay above.

I therefore would like the ability to hard-delete the file (i.e. without moving to a nonexistent trash folder). Obviously this is a risky option, so I'd suggest that this should be disabled by default, but could be enabled from the advanced preferences. Perhaps, for further security, it should be an option that does not stick when IINA is relaunched. Any thoughts?

**Comment by lhc70000** [comment] 2018-08-25 19:31
A new command `delete-current-file-hard` is proposed in #1934.

**Closed** 2018-09-12 05:38 UTC
Labels: feature: ui/ux, progress: fixed/implemented, type: discuss
