### ISSUE TITLE
Bug - Plays in half the resolution, despite being in "normal size"

### ISSUE THREAD

**Issue by ecchi** [lhc70000/iina#670] opened 2017-05-21 01:37 UTC
**System and IINA version:**

- macOS 10.12.5
- IINA 0.0.9
mbp 13" Retina (scale in System Preferences>Display>More Space)

**Expected behavior:**

Play file in native resolution, either by default or when in "normal size"

**Actual behavior:**
Plays in half the resolution. 1280x720 appears approximately as 640x360. All other players (mpv, vlc, QT, etc) play it in native resolution. Doesn't matter if the content is 1080p, or 720p. MKV or MP4, WMV or any other format. IINA is playing all content at "half" the resolution. Even when click view>normal size. To effectively match source, have to check "Double size".

**Steps to reproduce:**
Play any file

**How often does this happen?**
Every time

**Comment by saagarjha** [comment] 2017-05-21 01:38
Duplicate of #378. The reasoning behind this behavior can be found there.

**Closed by saagarjha** 2017-05-21 01:38 UTC
