### ISSUE TITLE
Resume playback

### ISSUE THREAD

**Issue by scalene-jl** [lhc70000/iina#169] opened 2017-01-14 12:04 UTC
It would be wonderful if iina should be able to resume playback at a later invocation.
Maybe with a bookmark plist file in ~/Library/Application Support ?

**Comment by megadr01d** [comment] 2017-01-14 16:01
Please search the issues before posting. Duplicate of https://github.com/lhc70000/iina/issues/128.

**Comment by lhc70000** [comment] 2017-01-15 07:36
Also duplicate with #10.

**Comment by lhc70000** [comment] 2017-01-19 11:15
Close due to duplication.

**Closed by lhc70000** 2017-01-19 11:15 UTC
Labels: duplicate
