### ISSUE TITLE
Flashing Blue Screen when Playing Videos

### ISSUE THREAD

**Issue by WANGJIEKE** [lhc70000/iina#1695] opened 2018-05-13 07:24 UTC
**System and IINA version:**

- macOS 10.13.4
- IINA 0.0.15.1

**Expected behavior:**
Play the video normally.

**Actual behavior:**
When the setting "Preference -> Codec -> Video -> Hardware Decoder" is set to "Auto" and the file is a .mkv file with HEVC encoding, the video flashes between blue screen and the content of the video. If the hardware decoder is disabled, the problem disappears.
当播放HEVC编码的mkv文件，且硬件解码器被设置为“自动”时，画面在蓝屏和实际视频内容之间不断闪烁。如果将硬件解码器设置成“禁用”，问题消失。

**Steps to reproduce:**
1. Set the Hardware Decoder to "Auto"
2. Play a .mkv file whose encoding is HEVC

- [ ] MPV does not have this problem.

**How often does this happen?**
Always, if the file is a .mkv file with HEVC encoding

**Comment by lhc70000** [comment] 2018-05-13 09:25
It should be related to FFmpeg 4.0 / mpv 0.28.

There're similar reports in https://github.com/mpv-player/mpv/issues/5755.

**Comment by jerkstore369** [comment] 2018-05-14 19:53
Link is dead?

**Comment by tmm1** [comment] 2018-05-16 17:32
I have a hacky fix in http://ffmpeg.org/pipermail/ffmpeg-devel/2018-May/229483.html, but would be better to figure out the root cause.

**Comment by saagarjha** [comment] 2018-05-16 19:39
Since this is an upstream issue, we're unlikely to merge it in here directly. I think the best course of action is to allow FFmpeg to come to consensus on how to resolve this issue, then wait for the changes to percolate downstream.

**Comment by tmm1** [comment] 2018-05-17 20:26
Here is an updated version of the patch if anyone would like to help test it: https://github.com/tmm1/FFmpeg/commit/d5624b0401b6d65de9cdfd726f5c6e7a1496a494

If it works, I will commit to FFmpeg master.

**Comment by tmm1** [comment] 2018-05-19 02:28
The fix has been merged to FFmpeg master: https://github.com/FFmpeg/FFmpeg/commit/8f146b526ff8d63adc02e1c5db15850f4589230b

**Comment by danshao** [comment] 2018-07-08 06:05
Still getting this issue with the 0.0.15.1 Build 69. Does not occur while using mpv.

**Comment by inflation** [comment] 2018-07-12 19:19
@danshao I believe build 69 does not build from ffmpeg HEAD, try build 80.

**Comment by frost134** [comment] 2018-07-27 16:04
Getting the issue too, totally the same situation.

**Comment by lhc70000** [comment] 2018-07-27 18:13
This issue happens in 0.0.15.1 or 1.0.0 beta1 which were built against FFmpeg 4.0. Please either **rollback to 0.0.15** or **upgrade to 1.0.0 beta3** if this bug annoys you.

**Closed by lhc70000** 2018-07-27 18:13 UTC
Labels: other: upstream

**Comment by fancyme** [comment] 2018-10-07 17:41
I have the same problem.
