### ISSUE TITLE
ESC key and "Use legacy full screen"

### ISSUE THREAD

**Issue by prohtex** [lhc70000/iina#1326] opened 2018-01-09 03:19 UTC
Hi, thank you for all your hard work on this excellent player. I am thrilled to find out about this project! I it continues and grows!

I noticed that when I have "Use legacy full screen" enabled, pressing ESC does not exit fullscreen, even when this is set in key bindings. Disabling "Use legacy full screen" makes ESC exit fullscreen as expected. I am hoping this can be fixed as I do not like native macOS fullscreen.

Thanks!

**Comment by alejx** [comment] 2018-01-09 03:21
Duplicate of #1107.

**Closed** 2018-01-13 06:11 UTC
Labels: feature: window, other: duplicate, progress: fixed/implemented
