### ISSUE TITLE
Please think about adding the airplay feature support

### ISSUE THREAD

**Issue by lvhailong** [lhc70000/iina#356] opened 2017-02-10 15:33 UTC
**System and IINA version:**

- macOS 10.12.2
- IINA 0.0.4

**Expected behavior:**
Please think about adding the airplay feature support. Then we can play any video on Mac and stream them to other devices in the same LAN.

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**Comment by HarukaMa** [comment] 2017-02-10 15:33
@lvhailong Please search for duplicate issues before opening a new issue.

**Comment by lvhailong** [comment] 2017-02-10 16:13
@HarukaMa Yes, I have searched the keyword "airplay" in this repository and just found this:
We couldn’t find any code matching 'airplay'

**Comment by inflation** [comment] 2017-02-10 16:15
@lvhailong Search for issues, folk.

**Comment by saagarjha** [comment] 2017-02-10 16:31
Duplicate of #63.

**Comment by alejx** [comment] 2017-03-16 23:54
Close due to duplication.

**Closed by alejx** 2017-03-16 23:54 UTC
Labels: duplicate
