### ISSUE TITLE
Desirable to add the current time of the system when fullscreen | 希望在全屏时能增加显示系统的当前时间

### ISSUE THREAD

**Issue by ajsong** [lhc70000/iina#435] opened 2017-02-23 00:35 UTC
例如全屏时在右上角增加系统的当前时间，而且一直显示（可在偏好设置控制是否一直显示），因为我经常需要看当前时间的（时间样式可以考虑是黑色字体、外发光、整体轻度半透明，当然字体不要太大），如果可以的话，也同时在这个时间隔壁增加显示 剩余时间或者影片总时间（根据播放控制栏里的时间类型来定），希望能考虑增加这个功能，谢谢，真心希望IINA能成为苹果上最优秀的播放器。
另外，使用鼠标控制音量，感觉滚动时音量变化的幅度太大了，从0滚两三下就已经变成100了。
------------------------------------------------------------------------------------
Such as fullscreen in the upper right corner to increase the current time of system, and always show (can be set in the Preference), because I often need to look at the current time (time style can be considered the black font, translucent, of course, the font is not too big), if you can, at the time to increase the display of the remaining time or the total time of the film (according to the Time in the playback control bar to set), hoping to consider adding this feature, thank you, really hope IINA can become the best player on the Apple.
By the way, the use of mouse to control the volume, feel the volume when rolling is too large, from 0 roll to 100 is too fast.

**Comment by megadr01d** [comment] 2017-02-23 14:24
Duplicate of https://github.com/lhc70000/iina/issues/179.

**Comment by lhc70000** [comment] 2017-02-24 10:28
And #281

**Comment by alejx** [comment] 2017-03-17 00:00
Close due to duplication.

**Closed by alejx** 2017-03-17 00:00 UTC
Labels: duplicate
